### ISSUE TITLE
[PaeParo-Mobile] 내부 안드로이드 소스코드 보는법 

### ISSUE THREAD

**Issue by seo0jjjjj** [PaeParo/PaeParo-Mobile#5]
안드로이드 메서드를 가져다 쓸 때, 어떻게 구현된지 내부 구현을 보면 이해하기 더 쉬운데, (특히 커스텀레이아웃) 
컨트롤 클릭을 통해서 보면

`
public void finish() {
    throw new RuntimeException("Stub!");
}
`

이런식을 볼 수 없는 경우가 있음.

Close Project후
![image](https://user-images.githubusercontent.com/54611807/231182900-dda7975a-fb5c-4a5b-bae6-ecb1f318dffb.png)
SDK Manager 들어가서

![image](https://user-images.githubusercontent.com/54611807/231181913-a62c5f6b-99fa-453f-8544-e27abf30adc5.png)
우측하단 Show Package Details 체크
타게팅하는 버전의 Sourses for Android 33 체크

![image](https://user-images.githubusercontent.com/54611807/231181965-6f6e87a2-62cf-43fd-b5b6-67d8c1d099b8.png)
Apply하고 다운로드하면

![image](https://user-images.githubusercontent.com/54611807/231182442-6ee13567-ba10-4723-b641-d256e9c53344.png)
매우 잘보임. 

![image](https://user-images.githubusercontent.com/54611807/231183198-4fbaceae-2fba-4673-898a-88e2c101cdd3.png)

**Comment by ILoveGameCoding** [comment]
추가로 해당 버전 SDK를 다운받아서 에뮬로 실행할 거라면, Show Package Details로 안 펼치고 그냥 선택하면 됩니당(SDK, Sources, 자신에게 맞는 Google API System Image가 자동으로 선택되서 들어갑니다)

**Comment by Blenbre777** [comment]
![image](https://user-images.githubusercontent.com/42365757/231195135-747a0830-6148-4923-8687-9d6e26d54724.png)

**Comment by tjralswo123** [comment]
굳
